### ISSUE TITLE
Error shown when product has not configuration steps and user clicks 'configure' button

### ISSUE THREAD

**Issue by patrickrwilson** [OCA/product-configurator#18]
Reproducing Steps:
Create a new configurable product.
Add attributes in the variants tab.
Click the 'Configure Product' button.

The following error shows:

  File "C:\Odoo\Odoo 14.0e\server\odoo\addons\product_configurator\wizard\product_configurator.py", line 670, in prepare_attrs_initial
    return attrs, field_name, custom_field, config_steps, cfg_step_ids
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Odoo\Odoo 14.0e\server\odoo\http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Odoo\Odoo 14.0e\server\odoo\http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
UnboundLocalError: local variable 'cfg_step_ids' referenced before assignment

**Comment by patrickrwilson** [comment]
Resolved with PR #19

**Comment by patrickrwilson** [comment]
Actually, this is being resolved in PR #16
