### ISSUE TITLE
Website Product Configurator error message

### ISSUE THREAD

**Issue by Woodlawnfurniture** [OCA/product-configurator#34]
**QWeb**
Error message:

Error to render compiling AST
MissingError: Record does not exist or has been deleted.
(Record: product.product(45315,), User: 14)
Template: website_product_configurator.cfg_product
Path: /t/t[1]
Node: **<t t-set="combination_info" t-value="product._get_combination_info(product_id=product.id, add_qty=add_qty or 1, pricelist=pricelist)"/>**
        
**The error occured while rendering the template website_product_configurator.cfg_product and evaluating the following expression: <t t-set="combination_info" t-value="product._get_combination_info(product_id=product.id, add_qty=add_qty or 1, pricelist=pricelist)"/>**

**Traceback**
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 806, in dispatch
    r = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 350, in checked_call
    result.flatten()
  File "/home/odoo/src/odoo/odoo/http.py", line 1242, in flatten
    self.response.append(self.render())
  File "/home/odoo/src/odoo/odoo/http.py", line 1235, in render
    return env["ir.ui.view"]._render_template(self.template, self.qcontext)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 1709, in _render_template
    return self.browse(self.get_view_id(template))._render(values, engine)
  File "/home/odoo/src/odoo/addons/website/models/ir_ui_view.py", line 411, in _render
    return super(View, self)._render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/home/odoo/src/odoo/addons/web_editor/models/ir_ui_view.py", line 28, in _render
    return super(IrUiView, self)._render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 1717, in _render
    return self.env[engine]._render(self.id, qcontext)
  File "/home/odoo/src/enterprise/web_studio/models/ir_qweb.py", line 44, in _render
    return super(IrQWeb, self)._render(template, values=values, **options)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_qweb.py", line 55, in _render
    result = super(IrQWeb, self)._render(id_or_xml_id, values=values, **context)
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 258, in _render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 338, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 806, in dispatch
    r = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 350, in checked_call
    result.flatten()
  File "/home/odoo/src/odoo/odoo/http.py", line 1242, in flatten
    self.response.append(self.render())
  File "/home/odoo/src/odoo/odoo/http.py", line 1235, in render
    return env["ir.ui.view"]._render_template(self.template, self.qcontext)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 1709, in _render_template
    return self.browse(self.get_view_id(template))._render(values, engine)
  File "/home/odoo/src/odoo/addons/website/models/ir_ui_view.py", line 411, in _render
    return super(View, self)._render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/home/odoo/src/odoo/addons/web_editor/models/ir_ui_view.py", line 28, in _render
    return super(IrUiView, self)._render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 1717, in _render
    return self.env[engine]._render(self.id, qcontext)
  File "/home/odoo/src/enterprise/web_studio/models/ir_qweb.py", line 44, in _render
    return super(IrQWeb, self)._render(template, values=values, **options)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_qweb.py", line 55, in _render
    result = super(IrQWeb, self)._render(id_or_xml_id, values=values, **context)
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 258, in _render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 338, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: Record does not exist or has been deleted.
(Record: product.product(45315,), User: 14)
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/api.py", line 790, in get
    return field_cache[record._ids[0]]
KeyError: 45315

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/fields.py", line 970, in __get__
    value = env.cache.get(record, self)
  File "/home/odoo/src/odoo/odoo/api.py", line 793, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'product.product(45315,).list_price'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/api.py", line 790, in get
    return field_cache[record._ids[0]]
KeyError: 45315

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/fields.py", line 970, in __get__
    value = env.cache.get(record, self)
  File "/home/odoo/src/odoo/odoo/api.py", line 793, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'product.product(45315,).product_tmpl_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/fields.py", line 1019, in __get__
    self.compute_value(recs)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/odoo/src/odoo/odoo/models.py", line 4063, in _compute_field_value
    field.compute(self)
  File "/home/odoo/src/odoo/odoo/fields.py", line 541, in _compute_related
    values = [first(value[name]) for value in values]
  File "/home/odoo/src/odoo/odoo/fields.py", line 541, in <listcomp>
    values = [first(value[name]) for value in values]
  File "/home/odoo/src/odoo/odoo/models.py", line 5666, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/src/odoo/odoo/fields.py", line 2483, in __get__
    return super().__get__(records, owner)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1000, in __get__
    raise MissingError("\n".join([
odoo.exceptions.MissingError: Record does not exist or has been deleted.
(Record: product.product(45315,), User: 14)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/api.py", line 790, in get
    return field_cache[record._ids[0]]
KeyError: 45315

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/fields.py", line 970, in __get__
    value = env.cache.get(record, self)
  File "/home/odoo/src/odoo/odoo/api.py", line 793, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'product.product(45315,).product_tmpl_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_website_product_configurator_cfg_product_419
  File "/home/odoo/src/odoo/addons/website_sale_stock/models/product_template.py", line 20, in _get_combination_info
    combination_info = super(ProductTemplate, self)._get_combination_info(
  File "/home/odoo/src/odoo/addons/website_sale/models/product.py", line 284, in _get_combination_info
    combination_info = super(ProductTemplate, self)._get_combination_info(
  File "/home/odoo/src/user/variant_price_system/models/product_template.py", line 81, in _get_combination_info
    list_price = product.price_compute('list_price')[product.id]
  File "/home/odoo/src/user/variant_price_system/models/product_product.py", line 30, in price_compute
    prices[product.id] = product[price_type] or 0.0
  File "/home/odoo/src/odoo/odoo/models.py", line 5666, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/src/odoo/odoo/fields.py", line 1021, in __get__
    self.compute_value(record)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/odoo/src/odoo/odoo/models.py", line 4063, in _compute_field_value
    field.compute(self)
  File "/home/odoo/src/odoo/odoo/fields.py", line 541, in _compute_related
    values = [first(value[name]) for value in values]
  File "/home/odoo/src/odoo/odoo/fields.py", line 541, in <listcomp>
    values = [first(value[name]) for value in values]
  File "/home/odoo/src/odoo/odoo/models.py", line 5666, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/src/odoo/odoo/fields.py", line 2483, in __get__
    return super().__get__(records, owner)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1000, in __get__
    raise MissingError("\n".join([
odoo.exceptions.MissingError: Record does not exist or has been deleted.
(Record: product.product(45315,), User: 14)

Error to render compiling AST
MissingError: Record does not exist or has been deleted.
(Record: product.product(45315,), User: 14)
Template: website_product_configurator.cfg_product
Path: /t/t[1]
Node: <t t-set="combination_info" t-value="product._get_combination_info(product_id=product.id, add_qty=add_qty or 1, pricelist=pricelist)"/>
        
![Product configurator Server error](https://user-images.githubusercontent.com/79715303/120944919-fcccaa00-c704-11eb-9ce7-d5242984d0f8.JPG)

**Comment by PCatinean** [comment]
Issue should be resolved with the above merged fix, can you confirm?

**Comment by Woodlawnfurniture** [comment]
Tested on odoo 14 enterprise and community no more error message. issue is resolved.
